### PR TITLE
Disable small ZSH aliases

### PR DESCRIPTION
**Pull request by KellerFuchs**
```
   ~daurnimator │ Ryan stares at KellerFuchs.
          ~Ryan │ KellerFuchs: i think what daurnimator is
                │ trying to say is that grml-etc-core aliases
                │ `ag` to apt-get upgrade; and I almost upgraded
                │ ny1
```

### CODE REVIEW

**Comment by KellerFuchs** [comment]
Also, why staring at me?

**Comment by KellerFuchs** [comment]
@ChickenNuggers @daurnimator Also, why stare at me?

**Comment by daurnimator** [comment]
> Also, why staring at me?

From another channel:

```
11:34:47	<daurnimator>	Use 'ag' instead of 'grep -r', much nicer.
11:35:42	<LordRyan>	it's asking me for root?..
11:35:54	<daurnimator>	?
11:35:58	<LordRyan>	oh
11:36:06	<LordRyan>	for some reason it's aliased to apt-get upgrade
11:37:06	<daurnimator>	did you grab some random's dotfiles full of aliases? :P
11:38:01	<daurnimator>	you might have to install ag. seems like you're on debian, so: apt install silversearcher-ag
11:38:42	<LordRyan>	daurnimator: grml-etc-core
11:38:48	<LordRyan>	blame KellerFuchs
```

**Comment by KellerFuchs** [comment]
Oh, I reject all blame, then.

**Pull request merged**
