### PR TITLE
git: Add git-fixup

### PR DESCRIPTION
**Pull request by KellerFuchs**
That's a convenient git command I [borrowed](https://blog.filippo.io/git-fixup-amending-an-older-commit/) from @FiloSottile.

- Modified to work on other shells than bash
- Modified not to run in the user's shell (but in a separate `sh`)  
  This avoids clobbering the user's environment
- Added an help message
- Reliably error-out

### CODE REVIEW

**Comment by daurnimator** [comment]
Why is this a dotfile rather than in /usr/bin or such?

**Comment by KellerFuchs** [comment]
- We have currently no way to deploy (& version) custom things to `/usr/bin` or `/usr/local/bin`.
- If we want the dotfiles to be reuseable outside of the shell servers, it makes sense to put it there.
- It lets users opt-out of the git customizations simply by unstowing the `git` directory, whereas removing a file from `/usr/bin` isn't possible.

**Comment by daurnimator** [comment]
> We have currently no way to deploy (& version) custom things to /usr/bin or /usr/local/bin.

Lets fix that?

> It lets users opt-out of the git customizations simply by unstowing the git directory, whereas removing a file from /usr/bin isn't possible.

This is not a customization, but a new command.

**Comment by KellerFuchs** [comment]
It's a customization in the sense that is changes the behaviour of the `git` command, and some people might prefer having completely-vanilla Git.

**Comment by KellerFuchs** [comment]
@daurnimator Aside from pedantic discussions about the word “customization”, do we agree this fits better in dotfiles?

**Comment by daurnimator** [comment]
> @daurnimator Aside from pedantic discussions about the word “customization”, do we agree this fits better in dotfiles (than in /usr/bin or /usr/local/bin)?

I don't think so: I don't like the idea of installing executables in .local/bin just because the system we've set up for ourselves makes it too hard to drop something in /usr/local/bin.

**Comment by KellerFuchs** [comment]
@daurnimator Eeeeh, my point is definitely not “it's hard to drop something in `/usr/local`” (it's not, we can easily manage that with Ansible and/or git).

1. Users who want to reproduce the same experience as on #! on their own machine should be able to do so reasonably easily.  
   Cloning `dotfiles` and stowing what you want fits that requirement.
2. Users who want their UX not to involve anything #!-specific can opt-out of it, either on a per-module basis or entirely.  
   They cannot opt out of your executable in `/usr/local/bin`.

**Comment by daurnimator** [comment]
btw, I tried this locally and you should add `-C commit.gpgSign=false` to the `git commit` line

**Comment by KellerFuchs** [comment]
Good point.

OTOH, you are going to be prompted for your passphrase anyhow during the rebase, if you have `commit.gpgSign=true` set in your config.

**Comment by KellerFuchs** [comment]
@daurnimator In case Github didn't notify you, I addressed your comment yesterday.
Any further remarks?

**Comment by daurnimator** [comment]
No. that was just a minor thing I noticed. I still disagree with the idea in general.
I'd sort of like @lrvick to opine here.

**Comment by KellerFuchs** [comment]
@daurnimator Then I would like to know what you disagree with, since the only thing you said is that “you don't like the idea of installing in `.local` because we can't deploy to `/usr`”, and didn't reply to any of the arguments in favor of putting it in dotfiles.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Ping?  :V

**Comment by KellerFuchs** [comment]
Yay, approval by timeout  :(

**Pull request merged**
