### PR TITLE
Run mutt under firejail

### PR DESCRIPTION
**Pull request by KellerFuchs**
This is part of hashbang/shell-etc#86.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
Don't merge, profile should go in shell-etc.
[See previous discussion.](https://github.com/hashbang/shell-etc/issues/86#issuecomment-206518874)

**Comment by KellerFuchs** [comment]
Merge after https://github.com/hashbang/shell-etc/pull/102 is deployed

**Comment by lrvick** [comment]
Seems straight forward enough and easy to revert if it ruins lives. +1

**Comment by gmcclins** [comment]
I think there is a permission problem.

> Error: cannot open profile file /etc/firejail/mutt.profile.

`4 -rw-r----- 1 root root  530 Aug 15 04:40 mutt.profile`

**Comment by KellerFuchs** [comment]
@gmcclins Thanks, there indeed was an issue.  It is now fixed  :-)

**Pull request merged**
