### PR TITLE
fish: Create default config with hashbangctl alias

### PR DESCRIPTION
**Pull request by alspore**
This might make it a bit easier to get started configuring fish when joining `hashbang.sh`.

### CODE REVIEW

**Comment by RyanSquared** [comment]
I don't use `fish` so I'm of no use checking. @KellerFuchs - do you use it?

**Comment by KellerFuchs** [comment]
I have absolutely no idea about `fish`.
(I have ideas about fish, and can make pretty decent sushi and sashimi, but that's something else entirely...)

@5paceManSpiff Thanks a lot for the contribution!  I will give it a try tomorrow (a bit too knackered today) and approve it I can confirm it works OK (else, I might ask to be told how to try the different things you set).
Could you also add comments explaining what the `/etc/sysconfig/i18n` bit and the `start_unicode` bit do?

**Comment by dpflug** [comment]
The `/etc/sysconfig/i18n` bit is just loading locale data.

The `unicode_start` command is used to kick off unicode support on a console, but I don't think it is applicable for us. The beginning of the script (on our systems) even checks if your tty is `/dev/console`, `/dev/vc*`, or `/dev/tty[0-9]*` before running. It'd be a noisy no-op.

**Comment by benharri** [comment]
woudn't it be more idiomatic to use a function for hashbangctl instead of an alias?

a la 
```
function hashbangctl
  sudo hashbangctl
end
```

**Comment by l2dy** [comment]
`hashbangctl` no longer exists on shell servers. Should this PR be closed?

**Comment by KellerFuchs** [comment]
@l2dy Absolutely, and thanks for the catch.

**Pull request closed without merging**
