### PR TITLE
weechat: Upgrade scripts

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by lrvick** [comment]
This is long overdue, but I wonder if a better approach would be to just have scripts auto install from upstream on first startup on weechat with '/plugin install ...'

**Comment by KellerFuchs** [comment]
@lrvick What I did in my own dotfiles is have [weechat/scripts](https://github.com/weechat/scripts) as a submodule.

If we don't want that, having scripts autoinstall would be weird/icky.  We can, however, make weechat upgrade scripts on first start, which might involve less hackery.

**Comment by RyanSquared** [comment]
that would be a simple command for startup, `/script update;/set <whatever option runs commands on startup> ""`

**Comment by KellerFuchs** [comment]
@RyanSquared My issue is more that you end up with a dirty dotfiles repo immediately.

**Comment by RyanSquared** [comment]
unless we kept scripts completely out of the repo? it would be simple to pump some commands into the FIFO to install scripts.

**Comment by KellerFuchs** [comment]
@RyanSquared At that point, it becomes install on first run.
The problem is that your installed scripts (and even more so, your *autoloaded* scripts) are definitely part of your weechat config and ought to be versionned.  I think I would be happier with using a submodule, since it means we (and users) can much more easily update scripts.

**Comment by RyanSquared** [comment]
Closing in favor of submoduling [weechat/scripts](/weechat/scripts).

**Pull request closed without merging**
